kos crd: always yield
In ap-cn-1 the kos is running into an error because:
  Error executing kos crd: ('KosQuery', 'monsoon3', 'ironic-node-update').
  Error: Error executing query: generator didn't yield
So it seems that whenever kos is unable to set a node to maintenace the
kos itself fails and it then also fails to update deployments. So we
also yield in an error case.