[Neutron] Fix nsxv3-agent sentry env indentation
The indentation needs to be 10 like in the "utils.trust_bundle.env"
later in the file. Otherwise, rendering the template generates invalid
YAML.

		yaml.parser.ParserError: while parsing a block mapping
		  in "<file>", line 41, column 9
		expected <block end>, but found '-'
		  in "<file>", line 52, column 9