[manila] change file type of ratelimit_backend_secret
Tools that are operating with .conf expect a certain key value format.
But this secret file holds a plain single value.

In my case it was the oslo config parser that choked like:

oslo_config.cfg.ParseError: at /etc/manila/ratelimit-backend-secret.conf:1, No ':' or '=' found in assignment