[Cinder] Add required resource filter for volume type
For Cinder train the /etc/cinder/resource_filters.json file
needs the entry for volume type, otherwise end uses can't
even get a list of volume types.

Without it non admins that run "cinder type-list" get the
following error.
ERROR: Invalid filters is_public are found in query options.

The feature/requirement was backported to train
https://github.com/openstack/cinder/blob/stable/train/etc/cinder/resource_filters.json#L14