Revert "nova-hypervisor-agents: Wait for certificate"
Seems to have created following error:

Error: Failed to render chart: exit status 1: Error: Unable to continue
with install: could not get information about the resource
ServiceAccount "" in namespace "monsoon3": resource name may not be
empty

This reverts commit a6b9d38c49d1025bf132abcdd4bcad5bea2d87b2.